"""
predict_expansion_candidates.py

Load the trained EBM and run inference on expansion candidates generated by
build_candidates.py. Produces predicted annual ridership for each top-100 city
that currently has no Amtrak station.

Assumptions:
  - GTFS rail features are zero for candidates (no existing service), not NaN.
    NaN in training means missing data; zero here means true absence of service.
  - All other features are populated by build_candidates.py.

Output: results/metrics/expansion_predictions.csv

Run after train and build_candidates have both completed:
    python src/predict_expansion_candidates.py
"""

import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from data_loader import ALL_FEATURES, load_stations

MODELS_DIR = ROOT / "models"
PROCESSED = ROOT / "data" / "processed"
METRICS_DIR = ROOT / "results" / "metrics"

MODEL_PATH = MODELS_DIR / "ebm_v1.pkl"
CANDIDATES_PATH = PROCESSED / "expansion_candidates.csv"
OUTPUT_PATH = METRICS_DIR / "expansion_predictions.csv"

# GTFS features that represent true zero (no service) for candidates
GTFS_FEATURES = [
    "weekly_departures",
    "num_routes_served",
    "is_terminal",
    "avg_dwell_time_sec",
    "service_span_hours",
    "avg_stop_sequence_pct",
    "num_directions",
    "avg_route_length_km",
    "max_route_length_km",
    "pct_long_distance",
]


def main():
    for path, desc in [
        (MODEL_PATH, "trained model — run train first"),
        (CANDIDATES_PATH, "expansion candidates — run build_candidates first"),
    ]:
        if not path.exists():
            sys.exit(f"Error: {path} not found ({desc})")

    # ── Load model ────────────────────────────────────────────────────────────
    print(f"Loading model from {MODEL_PATH} …")
    with open(MODEL_PATH, "rb") as f:
        bundle = pickle.load(f)
    ebm = bundle["ebm"]
    model_features = bundle["features"]
    print(f"  Model trained on {len(model_features)} features")

    # ── Load candidates ───────────────────────────────────────────────────────
    print(f"\nLoading expansion candidates from {CANDIDATES_PATH} …")
    candidates = pd.read_csv(CANDIDATES_PATH, low_memory=False)
    print(f"  {len(candidates)} candidates")

    # ── Zero-fill GTFS features (true absence of service, not missing data) ──
    for col in GTFS_FEATURES:
        if col in candidates.columns:
            candidates[col] = candidates[col].fillna(0)
        else:
            candidates[col] = 0

    # ── Apply same binary/numeric fills as data_loader for consistency ────────
    from data_loader import BINARY_IPCD_FEATURES
    for col in BINARY_IPCD_FEATURES:
        if col in candidates.columns:
            candidates[col] = candidates[col].fillna(0).astype(int)
        else:
            candidates[col] = 0

    if "modes_served" in candidates.columns:
        candidates["modes_served"] = candidates["modes_served"].fillna(0).astype(float)

    if "is_northeast_corridor" not in candidates.columns:
        candidates["is_northeast_corridor"] = 0

    if "station_type" not in candidates.columns:
        # Fill with the most common type from training data
        stations = load_stations()
        candidates["station_type"] = stations["station_type"].mode()[0]

    # ── Build feature matrix using only features the model knows ─────────────
    available = [f for f in model_features if f in candidates.columns]
    missing_from_candidates = [f for f in model_features if f not in candidates.columns]
    if missing_from_candidates:
        print(f"\n  Warning: {len(missing_from_candidates)} model features not in candidates "
              f"(will be NaN): {missing_from_candidates}")
        for col in missing_from_candidates:
            candidates[col] = np.nan

    X = candidates[model_features].copy()

    # ── Predict ───────────────────────────────────────────────────────────────
    print(f"\nRunning inference on {len(X)} candidates …")
    log_preds = ebm.predict(X)
    predicted_ridership = np.expm1(log_preds).astype(int)

    # ── Assemble output ───────────────────────────────────────────────────────
    output = pd.DataFrame({
        "city": candidates["City"],
        "state": candidates.get("state_abbr", pd.Series([np.nan] * len(candidates))),
        "population": candidates.get("pop", pd.Series([np.nan] * len(candidates))),
        "predicted_annual_ridership": predicted_ridership,
        "predicted_log_ridership": log_preds.round(4),
        "has_intercity_bus": candidates["has_intercity_bus"].astype(int),
        "has_transit_bus": candidates["has_transit_bus"].astype(int),
        "has_air_connection": candidates["has_air_connection"].astype(int),
        "metro_pop": candidates["metro_pop"],
        "num_amtrak_stations_80km": candidates["num_amtrak_stations_80km"],
    }).sort_values("predicted_annual_ridership", ascending=False).reset_index(drop=True)

    METRICS_DIR.mkdir(parents=True, exist_ok=True)
    output.to_csv(OUTPUT_PATH, index=False)
    print(f"\nPredictions saved to {OUTPUT_PATH}")

    print(f"\nTop 15 expansion candidates by predicted ridership:")
    print(output.head(15).to_string(index=False))


if __name__ == "__main__":
    main()
